### ISSUE TITLE
Parameter optimization for tempo, beats, onset

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#119]
We should systematically optimize the default parameters for tempo estimation and beat tracking, as was previously done for onset detection.

Since the beat tracker uses tempo estimation as a subroutine, I propose that we first optimize tempo, and then fix the parameters for beat tracking.

**Comment by bmcfee** [comment]
While we're at it: how about redoing the `onset_detect` sweep for `hop_length=512`, so that it more easily lines up with everything else?

**Comment by bmcfee** [comment]
Beat / tempo:

- Parameter optimization on SMC2 + Beatles, sweeping over the following parameters
  - onset: aggregate, fmax, n_mels
  - tempo: ac_size, std_bpm
  - beat_track: tightness
- Results say to update the default parameters as follows:
  - aggregate was `np.mean`, now `np.median`
  - fmax is `8000.0` by default (for onset_envelope calculation).  Was `None` (sr/2) before.
  - n_mels is still 128
  - ac_size was 4 seconds, now 2.
  - std_bpm stays at 1.0
  - tightness was 400, now 100.

These settings are now in eeba8651004db0cb396ff023b6e5e3231113ec9c

Next up: onsets

**Comment by bmcfee** [comment]
Onsets:

* Parameter optimization on @craffel's dataset, sweeping over
  * aggregate, fmax, n_mels
  * delta

Lucky coincidence, the parameters to onset strength lined up exactly with those chosen for beat tracking: `median, 8000, 128`.

The best `delta` parameter is now 0.01, owing to the increased sparsity from switching `mean` to `median`.

@craffel when you get a minute, can you dig up the scores you had previously on the onset data so I can compare and make sure we're still good?

**Comment by craffel** [comment]
I got a maximal mean F-measure over the dataset you have of .7449, but I was doing a parameter sweep over all of `peak_pick`'s parameters, not just `delta`, and none of `onset_strength`'s parameters.  The default parameter values in `onset_detect` are the ones I found: https://github.com/bmcfee/librosa/commit/e9fa5eb511012177f46a97e83ede6d4ecb4f23ce

**Comment by bmcfee** [comment]
O_o

that's much higher than what I'm seeing.

I left the pre_ and post_ parameters alone, since A) that's a huge parameter space for a tiny problem (duh, lern 2 machine lern nubcakes) and B) they should (!) be reasonably stable when represented in time (not frames).

Maybe a bigger parameter sweep is in order...

**Comment by craffel** [comment]
> Maybe a bigger parameter sweep is in order...

You could run https://github.com/CPJKU/SuperFlux/blob/master/SuperFlux.py over this dataset to see what kind of results are achieved by a pretty similar system which is pretty heavily hyperparameter-optimized.

**Comment by bmcfee** [comment]
As a sanity check, I rolled back to hop=64 and swept delta with the remaining stock parameters.  I get a top mean F of 0.361, which is closer to what I'm seeing now.

**derp** upon closer inspection, i forgot to log everything.  Rerun...

**Comment by bmcfee** [comment]
putting the log back in only gets to F=0.391.  Something seems wrong.

**Comment by craffel** [comment]
Yeah, something is wrong.  I just re-ran my script from before and got a mean f-measure of 0.7407...  Here's a snippet which will hopefully reproduce that score for you: https://gist.github.com/craffel/2c76e74589e99c3f1246 (apologies if it doesn't work off the bat, it's copied from my ipynb).  There is some special sauce there in terms of normalizing the onset strength signal and adjusting the onset locations by a offset which I'm not sure is the same as is done in `onset_detect`.

**Comment by bmcfee** [comment]
You're at 16KHz?  Wut?

**Comment by craffel** [comment]
> You're at 16KHz? Wut?

I'm not sure why, but I'd be surprised if that cut the F-measure in half.

**Comment by bmcfee** [comment]
also https://gist.github.com/craffel/2c76e74589e99c3f1246#file-gistfile1-py-L15 is running at the default sampling rate (22KHz), but your audio is loaded at 16.  I'm amazed this works.  O_O

Do you happen to have a revision/librosa version/timestamp on that experiment?  I think https://gist.github.com/craffel/2c76e74589e99c3f1246#file-gistfile1-py-L27 should no longer be necessary.

**Comment by craffel** [comment]
> Do you happen to have a revision/librosa version/timestamp on that experiment? I think https://gist.github.com/craffel/2c76e74589e99c3f1246#file-gistfile1-py-L27 should no longer be necessary.

Oops, this was a copy/paste error.  The `SR = 16000` was for some diagnostics onset + clicks files I was creating.  The onset strength signal pre-computations I was doing was with default sampling rate everywhere.  I've updated to reflect this.

> Do you happen to have a revision/librosa version/timestamp on that experiment? I think https://gist.github.com/craffel/2c76e74589e99c3f1246#file-gistfile1-py-L27 should no longer be necessary.

No, but I just ran this gist with the latest develop commit and that gave .74 F-measure.

> edit and your conversion from frames to time is also going to be off, since the sr parameter is missing from https://gist.github.com/craffel/2c76e74589e99c3f1246#file-gistfile1-py-L28 as well. Maybe this plus the above cancel each other out, somehow?

Maybe, I don't know.  Maybe it was from before you added the `sr` kwarg to `frames_to_time`, so I needed to add the correction myself. I did this experiment around 3/29/13, I think.

**Comment by bmcfee** [comment]
Ok.  I stft centering was added in january 2014 #71 , so that makes sense.

frames_to_time should always have had a sr keyword though.

Still investigating over here... maybe something went screwy in my data transfer?  Would you mind gisting the per-track scores (preferably zipped against filename)?

**Comment by bmcfee** [comment]
Aha!  Some of these .onsets files are row-major and some are column major.

That would certainly do it.

**Comment by bmcfee** [comment]
... if only someone would come along and solve annotation storage....

**Comment by craffel** [comment]
> Would you mind gisting the per-track scores (preferably zipped against filename)?

https://gist.github.com/craffel/2c76e74589e99c3f1246#file-gistfile2-txt

> Aha! Some of these .onsets files are row-major and some are column major.

They come from I think four or five different collections; this was in the pre-`mir_eval.io` days so I used `np.genfromtext` which did the trick on all of the files.

**Comment by bmcfee** [comment]
Roger that.  I'm back up at 0.749, with almost identical parameters to those described before.  (Delta is 0.07 now.)

Thanks!

**Comment by craffel** [comment]
For fair comparison, it might be worth documenting which datasets each algorithm was optimized over in the docstrings (e.g., if I want to compare beat detection results with a hypothetical new fancy beat tracker to those produced by librosa on SMC, it's worth noting that the librosa beat tracker was hyperparameter optimized over SMC).
