### ISSUE TITLE
ifgram returns negative frequencies

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#137]
Title says it all:
```python
>>> y, sr = librosa.load(librosa.util.example_audio_file())
>>> F, D = librosa.ifgram(y)
>>> F.size
2713175
>>> F[F < 0].size
1949
```

The negatives are huge, as well:
```python
>>> F[F < 0]
array([ -2.236e+02,  -2.130e+02,  -4.991e-01, ...,  -1.862e+03,
        -5.777e+03,  -2.168e+03])
```

Note that `librosa.ifgram` passes regression tests against @dpwe's matlab implementation, so this is probably an algorithmic issue rather than translation.

**Comment by bmcfee** [comment]
Agreed.

So far, I've dug up some numerical instabilities that crop up from defining `freq_angular` by
```python
freq_angular = np.linspace(0, 2 * np.pi, n_fft, endpoint=False)
```
instead of
```python
freq_angular = np.linspace(0, 2 * np.pi, n_fft, endpoint=True)
```

The former (used to match the matlab implementation) introduces some jitter into the real component of `fft(d_window)`: ![here](http://i.imgur.com/uq74B6P.png)

The jitter is relatively small, but it is of comparable magnitude to the power normalization in low-energy bins.

**Comment by dpwe** [comment]
Isn't that just a scaling thing?  Isn't the "jitter" because that's the
only graph where the vertical axis is 1e-15?

  DAn.

**Comment by bmcfee** [comment]
Yeah, fair enough.  Swapping it doesn't fix the bug.  The hunt continues...

**Comment by bmcfee** [comment]
More investigation re: power normalization.  It looks like there are two distinct failures happening here.

1. Low-frequency bins are dipping negative, even with high energy.  These dips tend to be relatively small in magnitude.
2. High-frequency bins jumping way down low.  This is a confirmed stability problem:

```python
>>> np.vstack([power[F < 0], F[F < 0]]).T
array([[  6.195e-03,  -2.236e+02],
       [  1.153e-02,  -2.130e+02],
       [  2.381e-02,  -4.991e-01],
       [  3.787e-02,  -5.701e+00],
       [  3.241e-03,  -4.430e+02],
       [  4.744e-02,  -5.317e+00],
       [  1.412e-01,  -2.409e+02],
       [  1.783e-01,  -1.458e+02],
       [  3.400e-02,  -6.890e+02],
       [  1.125e-05,  -1.349e+03],
       [  1.376e-07,  -2.012e+05],
       [  2.255e-08,  -1.233e+04],
       [  1.486e-08,  -2.031e+03],
       [  4.496e-08,  -1.986e+02],
       [  2.432e-08,  -8.566e+03],
       [  8.196e-09,  -5.295e+03],
       [  3.607e-08,  -8.788e+03],
       [  2.295e-08,  -2.127e+03],
       [  7.356e-09,  -7.129e+04],
       [  4.449e-08,  -3.181e+03],
       ..., 
       [  5.301e-09,  -2.896e+04],
       [  2.242e-08,  -4.073e+03],
       [  1.906e-08,  -2.532e+03],
       [  1.973e-08,  -9.952e+03],
       [  1.468e-08,  -7.739e+03],
       [  3.097e-09,  -4.875e+03],
       [  2.533e-09,  -1.845e+04],
       [  1.008e-08,  -2.583e+04],
       [  3.679e-08,  -4.105e+03],
       [  2.587e-08,  -6.092e+03],
       [  3.223e-08,  -1.904e+03],
       [  1.013e-08,  -1.974e+03],
       [  4.374e-08,  -1.925e+03],
       [  8.247e-09,  -9.170e+03],
       [  4.681e-09,  -4.068e+03],
       [  9.395e-09,  -4.486e+04],
       [  5.463e-09,  -4.318e+04],
       [  9.583e-09,  -1.071e+04],
       [  9.263e-09,  -1.526e+03],
       [  7.011e-09,  -3.002e+04]])
```

The first column shows the power at a spectrogram bin corresponding to a negative ifgram frequency, and the right column shows the corresponding frequency.  When power is reasonably large (> 1e-5), the frequencies are "reasonable" in the sense that they're within an order of magnitude of the bin width.

When power goes to 0, we hit a numerically unstable normalization operation.

For (1), making the minimum energy threshold more aggressive should resolve the issue.  However, this will not fix the problem for (1).  Any suggestions?

**Comment by bmcfee** [comment]
Picking this one up again, and I still don't understand what exactly is going on.

My current best guess is that this line of code:
```python
    if_gram = ((freq_angular[:n_fft//2 + 1]
                + (stft_matrix * diff_stft).imag / power)
               * float(sr) / (2.0 * np.pi))
```
needs to be reworked.  The term
```python
(stft_matrix * diff_stft).imag / power)
```
should compute a (fractional) bin offset from the center bin (freq_angular), which then gets scaled back into linear frequency.

Does it ever make sense for the bin offset to be outside of [-1, 1]?  ie, do we want to assign frequency from bins more than one bin away?  It seems like this should never happen due to the power normalization and scaling of `d_window` in constructing `diff_stft`, but maybe I'm missing something.

If the bin offset *should* always be within +- 1, what's the right way to force it?  Clipping, or remainder mod 1?

**Comment by dpwe** [comment]
No, you don't want to limit it to be +/- 1 bin.  Part of the point of
IF is to be able to find several bins dominated by the same frequency
component (due, e.g., to window spreading).  So you want the reported
frequency to be able to be outside the nominal range for that bin.

Negative frequencies are part of the deal here.  Why exactly do you
want to get rid of them?  They violate some basic sanity check? But
maybe the natural sanity check is, in fact, inappropriate here.

I agree that the negative values are likely worthless; If you don't
want negative values coming out, put a floor on the output.  But then
your sanity check is trivial.

In general, if the bin has nontrivial energy, we'd expect the
frequency to be nonnegative.  So for instance:

>>> Dabs = np.abs(D)
>>> print np.min(F[Dabs>np.max(Dabs/10)])
38.4428422675

but it doesn't work for Dabs/100.

Probably it's limited to the very low frequency bins, though (where
it's easy to wander into negative territory).  If you exclude the
lowest 10 bins, then it does work for Dabs/100:

>>> Dabs = np.abs(D)
>>> Dabs[:10, :] = 0.0
>>> print np.min(F[Dabs>np.max(Dabs/100)])
37.4918609015

.. but not for Dabs/1000.

 DAn.

**Comment by bmcfee** [comment]
> No, you don't want to limit it to be +/- 1 bin.  Part of the point of
> IF is to be able to find several bins dominated by the same frequency
> component (due, e.g., to window spreading).  So you want the reported
> frequency to be able to be outside the nominal range for that bin.
> 
> Negative frequencies are part of the deal here.  Why exactly do you
> want to get rid of them?  They violate some basic sanity check? But
> maybe the natural sanity check is, in fact, inappropriate here.

Originally, I wanted to get rid of them because they were screwing up the statistics for tuning estimation. Now they just bother me. :)

Anyway, I agree on the bin deviation limit (glad I asked).  In those settings though, shouldn't we expect some continuity in the estimated frequencies?  Instead, I'm seeing wild flapping (not just at the edges), which coincide with numerical instability.

To get a better picture of what's going on here, I made a scatter plot of log-power (relative to max) vs frequency bin for the cells with negative frequency estimates

![here](http://i.imgur.com/FjAGUl5.png)

The ones in the upper-left are clearly numerical problems, and should be thresholded out.

The ones in the bottom are trickier, since they reach up pretty far in the spectrum.  As you point out, this happens mainly at low energies, but there isn't an obvious (to me) threshold.

**Comment by bmcfee** [comment]
Here are a few things we can do, which break backwards compatibility, but I think are worth it:

- Change the if_gram calculation from 
```python
if_gram = ((freq_angular[:n_fft//2 + 1] + (stft_matrix * diff_stft).imag / power)
               * float(sr) / (2.0 * np.pi))
```
to
```python
mag, phase = magphase(stft_matrix)
if_gram = ((freq_angular[:n_fft//2 + 1] + (phase * diff_stft).imag / mag)
               * float(sr) / (2.0 * np.pi))
```
This is (ideally) equivalent, but more stable than dividing by squared magnitude.  This already breaks backwards compatibility, but should pass `allclose` with a still reasonable tolerance (1e-3 seems to work on the example track).

- Add a minimum energy threshold: anything below the threshold will just get the default (bin center) frequency estimate.  We can do this either in absolute terms, like DAn does above, or absolute terms based on floating point precision. (It's easy to support both, following the pattern used in `logamplitude` for reference power.)  Setting this to `1e-6` suffices to knock out the high-frequency/low-energy noise in the plot I posted above, but the low-frequency noise remains.

- Add an option to brute-force the frequency estimates to the range `[0, sr/2)`.  This would knock out everything else, ie, the bottom-right corner of the above plot.  This is obviously ugly.

**Comment by dpwe** [comment]
On Mon, Feb 23, 2015 at 3:00 PM, Brian McFee <notifications@github.com> wrote:
> Here are a few things we can do, which break backwards compatibility, but I
> think are worth it:
>
> Change the if_gram calculation from
>
> if_gram = ((freq_angular[:n_fft//2 + 1] + (stft_matrix * diff_stft).imag / power)
>                * float(sr) / (2.0 * np.pi))
>
> to
>
> mag, phase = magphase(stft_matrix)
> if_gram = ((freq_angular[:n_fft//2 + 1] + (phase * diff_stft).imag / mag)
>                * float(sr) / (2.0 * np.pi))
>
> This is (ideally) equivalent, but more stable than dividing by squared
> magnitude. This already breaks backwards compatibility, but should pass
> allclose with a still reasonable tolerance (1e-3 seems to work on the
> example track).

This doesn't seem like such a big improvement.  Our problem comes from
small projections of the complex product of stft_matrix[i, j] and
diff_stft[i, j], which is then scaled by <power>.  <phase> is
(apparently) stft_matrix/np.abs(stft_matrix), so we can divide down
both numerator and denominator by <mag> = np.abs(stft_matrix), but
apart from running off the end of the dynamic range of floating point,
it's not clear to me how much this can help.

More broadly, the instantaneous frequency calculation is doing
something like comparing the average phase over the whole window
(angle(stft)) with the change in phase between the first and second
halves (angle(diff_stft)); the weighting of points within the window
is quite different between the two components, so I think it's not a
scandal that the values are sometimes way off.  I'm not sure we should
be trying to hide this.

We could have a soft regression to the bin center by dividing by
(power + epsilon) for some epsilon.  But that also introduces
systematic error for other values.

Actually, I think the unreliability is not a function of the absolute
power level, but perhaps the difference in energy between the first
and second halves of each window.  But then, even if we came up with
an index of reliability of IF estimate (which would be new research),
what would we do?  Mask out at some threshold?

  DAn.

**Comment by bmcfee** [comment]
> so we can divide down
> both numerator and denominator by <mag> = np.abs(stft_matrix), but
> apart from running off the end of the dynamic range of floating point,
> it's not clear to me how much this can help.

Yes, this is what I meant by "numerical instability" before.  It does help, but doesn't fix everything, as you mention.

> the weighting of points within the window
> is quite different between the two components, so I think it's not a
> scandal that the values are sometimes way off.  I'm not sure we should
> be trying to hide this.

Iduno, results like this just look wrong to me, and if we can fix them, I think we should:
![Imgur](http://i.imgur.com/C8tGCoX.png)



> Actually, I think the unreliability is not a function of the absolute
> power level, but perhaps the difference in energy between the first
> and second halves of each window.  But then, even if we came up with
> an index of reliability of IF estimate (which would be new research),
> what would we do?  Mask out at some threshold?

That's an interesting idea; but yes, I think discarding unreliable estimates would make sense.

Anyway, I suspect it's probably not worth investing much time/thought into this, but I'd like to get this function as stable as possible before purging it from my brain cache.

**Comment by dpwe** [comment]
Yeah, that's quite compelling.  Let me try to look into the background.
Although I reference the Abe paper, I think it's the same principle
described in eqn. 7 of Flanagan & Golden 1966
https://www.ee.columbia.edu/~dpwe/e6820/papers/FlanG66.pdf
which is just differentiation by parts?

  DAn.

**Comment by dpwe** [comment]
No, it's not the same. F&G take first-order difference of successive
frames; Abe actually takes the derivative of the window function: eqn. (7)
in
https://www.ee.columbia.edu/~dpwe/e6820/papers/AbeKI96-if.pdf

My best guess is the errors (between analysis & actual values) creep in
through the discretization.

That value that's miles outside the range must come from a very small
denominator.  So maybe the enemy is not all negative values, but only the
ones that are exceptionally large.  Masking by denominator <
max(denominator)/1e6 or something ought to handle them?

  DAn.

**Comment by bmcfee** [comment]
> Masking by denominator <
> max(denominator)/1e6 or something ought to handle them?

Yup, that's basically what I was proposing with the first and second modifications above.  The last modification is a last-ditch, clean-up-the-leftovers fix to handle the small negative values at the bottom of the spectrum.

**Comment by dpwe** [comment]
OK, I agree.  Actually, maybe simply clipping everything at [0, sr/2]
is enough: if the value strayed to those limits, we want it to be easy
to spot.  "Softening" a straying value so it just avoids hitting the
edges doesn't seem like it's helping much (although masking values
that might be in the acceptable range but are basically junk seems
like a good idea too).

  DAn.
