### ISSUE TITLE
decompose tests occasionally fail

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#138]
The unit test for `librosa.decompose` can occasionally fail, due to the randomness in the default NMF method.

This can be circumvented by seeding the random number generator within the unit test.

**Comment by bmcfee** [comment]
@dawenl this is currently the only failing test in develop... feel like fixing it?

**Comment by dawenl** [comment]
Yes, we can set the seed fixed. I will take a look at it over the weekend.

**Comment by dawenl** [comment]
I think it's fixed now. Could you check as well?

**Comment by bmcfee** [comment]
Looks good. thanks!
