### ISSUE TITLE
Memory efficiency for util.match_*

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#143]
The matching utilities use numpy outers to construct large arrays, and then select out a minimizer among each row.  For large sets of events (eg, onset frames over a long track), this can become infeasible.

We should either operate per-row, or slice into reasonable-sized blocks as is done in `librosa.core.stft`.

- [x] match_events
- [x] match_intervals

**Comment by dpwe** [comment]
Outers seems to be a bit of a disaster. For tasks large enough to care
about the speed-up, it seems to kill by memory.

I felt so clever using outers in audfprint.py.  But then it wouldn't work
on large files. And when I rewrote with a loop, it got much faster
(swapping bound, I guess).

  DAn.

**Comment by bmcfee** [comment]
I wouldn't say it's a disaster, just that it needs to be used carefully  (That is, only when quadratic memory consumption is okay.)

For event/interval matching at the level of annotations, quadratic memory was acceptable, since items numbered typically in the hundreds (worst-case).  This only became a problem when I started using the matching code for zero-crossing alignment (see #142), when there are tens of thousands of target events.
