### ISSUE TITLE
feature.delta or deltas.m off by one?

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#155]
In writing tests for `feature.delta`, I came across a possible off-by-one column error.

Here's the output of the matlab version [deltas.m](http://labrosa.ee.columbia.edu/matlab/rastamat/deltas.m):
```matlab
>> X = [0:4]' * [0:4]

X =

     0     0     0     0     0
     0     1     2     3     4
     0     2     4     6     8
     0     3     6     9    12
     0     4     8    12    16

>> deltas(X, 3)

ans =

     0     0     0     0     0
     1     2     2     2     1
     2     4     4     4     2
     3     6     6     6     3
     4     8     8     8     4
```

and the librosa implementation:
```python
>>> X = np.multiply.outer(np.arange(5.), np.arange(5.))
>>> X
array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   1.,   2.,   3.,   4.],
       [  0.,   2.,   4.,   6.,   8.],
       [  0.,   3.,   6.,   9.,  12.],
       [  0.,   4.,   8.,  12.,  16.]])
>>> librosa.feature.delta(X, width=3)
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  2.,  2.],
       [ 0.,  2.,  4.,  4.,  4.],
       [ 0.,  3.,  6.,  6.,  6.],
       [ 0.,  4.,  8.,  8.,  8.]])
>>> librosa.feature.delta(X, width=3, trim=False)
array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  2.,  2.,  2.,  1.,  0.],
       [ 0.,  0.,  0.,  2.,  4.,  4.,  4.,  2.,  0.],
       [ 0.,  0.,  0.,  3.,  6.,  6.,  6.,  3.,  0.],
       [ 0.,  0.,  0.,  4.,  8.,  8.,  8.,  4.,  0.]])
```

When trimming is disabled, you can see that the deltas.m output is contained in librosa's, but shifted right by one column.  I'm inclined to think that librosa is doing the right thing here, since I would expect the change at first column to be 0 (if we adhere to the semantics of edge-copy padding).

Is this just a matter of convention, or an actual error?  If so, should we change it to match matlab (and potentially other implementations), or leave it as is?

**Comment by bmcfee** [comment]
I've added unit tests for the simplest case of width=3, and integrating back librosa's output gives the input (as expected).

**Comment by dpwe** [comment]
Deltas is not supposed to be first-order difference (use np.diff if you
want something you can "integrate back"). It's supposed to be an estimate
of the local slope, based on a symmetric weighted window. I'm pretty sure
that the Matlab behavior is right. I also think that, given a symmetric,
"stationary" input, we want a symmetric output.

  DAn.

**Comment by bmcfee** [comment]
> Deltas is not supposed to be first-order difference (use np.diff if you
> want something you can "integrate back"). It's supposed to be an estimate
> of the local slope, based on a symmetric weighted window.

Maybe I'm not understanding the distinction.  Shouldn't `width=3` act exactly like a centered first-order difference (up to normalization), and in that sense, shouldn't integration recover the original input (if it's actually linear)?

Also, pardon the tangent (zing!), but if it's an estimate of the "slope", shouldn't it be normalized by the `width` (rise-over-run and all)?  It seems strange that changes in `width` cause changes in magnitude, when all it's doing is increasing the range over which it's estimating the local slope.

> I'm pretty sure
> that the Matlab behavior is right.

Ok, I can get behind that, if it's explicitly intended as a centered operator.  That's probably the whole source of my confusion in the first place.

**Comment by dpwe** [comment]
I think it should return the same value, modulo the smoothing, as
width increases.  And, moreover, that value should be 1.0 when the
input is np.arange(num_points).  If we don't have that already ...
then the whole world is wrong.

  DAn.

**Comment by bmcfee** [comment]
Well, currently, neither implementation normalizes by width... so yep.

If we throw that in, then both versions basically do the right thing, ignoring the off-by-one shift that started this thread, and ignoring the non-linearity due to edge-copy padding the input (as opposed to linear extrapolation).

**Comment by bmcfee** [comment]
(nb: normalization should be by `floor(width//2)`, not `width`)

**Comment by bmcfee** [comment]
Changes are implemented but not yet pushed.  Here's a notebook explaining the changes and giving a simple demo on a linear function.

http://nbviewer.ipython.org/gist/bmcfee/f1ef5fc8d4e8356f9961

Does this look correct?

**Comment by dpwe** [comment]
I don't know what 'untrimmed' is for, but 'trimmed' looks great.

  DAn.

**Comment by bmcfee** [comment]
Untrimmed output there probably has no real use (maybe even less utility than `full` mode in fftconvolve), but it's helpful for debugging.

Anyway, unit tests are updated and everything checks out.  Thanks for the eyeballs!

Closing this one.
