### ISSUE TITLE
Onset detection errors with large hop size

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#166]
This relates to #161 and #163.

If you increase the hop size from 64 to 512, things go bad:

```python
In [1]: import librosa

In [2]: y, sr = librosa.load(librosa.util.example_audio_file())

In [3]: o_env = librosa.onset.onset_strength(y, sr=sr, hop_length=512)

In [4]: librosa.onset.onset_detect(onset_envelope=o_env, sr=sr, hop_length=512)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-8dd0fb83fee1> in <module>()
----> 1 librosa.onset.onset_detect(onset_envelope=o_env, sr=sr, hop_length=512)

/home/bmcfee/lib/python/librosa/onset.py in onset_detect(y, sr, onset_envelope, hop_length, **kwargs)
    136 
    137     # Peak pick the onset envelope
--> 138     return util.peak_pick(onset_envelope, **kwargs)
    139 
    140 

/home/bmcfee/lib/python/librosa/util/utils.pyc in peak_pick(x, pre_max, post_max, pre_avg, post_avg, delta, wait)
    848 
    849     if post_max <= 0:
--> 850         raise ValueError('post_max must be positive')
    851 
    852     if post_avg <= 0:

ValueError: post_max must be positive
```

This happens because the `post_max` parameter rounds down to 0 by default, which is no longer permitted.  Overriding the default causes another error:

```python
In [5]: librosa.onset.onset_detect(onset_envelope=o_env, sr=sr, hop_length=512, post_max=1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-ccaabc4fc675> in <module>()
----> 1 librosa.onset.onset_detect(onset_envelope=o_env, sr=sr, hop_length=512, post_max=1)

/home/bmcfee/lib/python/librosa/onset.py in onset_detect(y, sr, onset_envelope, hop_length, **kwargs)
    136 
    137     # Peak pick the onset envelope
--> 138     return util.peak_pick(onset_envelope, **kwargs)
    139 
    140 

/home/bmcfee/lib/python/librosa/util/utils.pyc in peak_pick(x, pre_max, post_max, pre_avg, post_avg, delta, wait)
    864                                                      mode='constant',
    865                                                      origin=int(max_origin),
--> 866                                                      cval=x.min())
    867 
    868     # Get the mean of the signal over a sliding window

/usr/local/lib/python2.7/dist-packages/scipy/ndimage/filters.pyc in maximum_filter1d(input, size, axis, output, mode, cval, origin)
    863     output, return_value = _ni_support._get_output(output, input)
    864     if (size // 2 + origin < 0) or (size // 2 + origin >= size):
--> 865         raise ValueError('invalid origin')
    866     mode = _ni_support._extend_mode_to_code(mode)
    867     _nd_image.min_or_max_filter1d(input, size, axis, output, mode, cval,

ValueError: invalid origin
```

**Comment by craffel** [comment]
Both of these issues are basically because we need to re-run the param optimization.  The first issue is because of the recent changes in #163 - the param optimization was done assuming that `post_max` and `post_avg` could be `0`, and for whatever reason chose `post_max = 0` as the best value, which causes a `ValueError` now.  The second issue is partially because the param optimization was done using a hop size of 64, and the chosen values don't really make sense for a hop size of 512 - 512 samples is 23.2 ms at 22 kHz. and the chosen `pre_max` (for example) is 30 ms, which translates to 1 sample of the onset envelope.  It's also partially because the call to `peak_pick` in `onset_detect` is passing float values, which is not valid according to the docstring.  I think we should probably fix this in `onset_detect` by rounding and casting to int, but we could also fix it in `peak_pick` by doing the same.  I've created a PR for this #167

**Comment by bmcfee** [comment]
> The second issue is partially because the param optimization was done using a hop size of 64, and the chosen values don't really make sense for a hop size of 512 - 512 samples is 23.2 ms at 22 kHz. and the chosen pre_max (for example) is 30 ms, which translates to 1 sample of the onset envelope.

One sample for pre_max (and post_max) should still be valid though, right?  Wouldn't that just correspond to a localmax?



> It's also partially because the call to peak_pick in onset_detect is passing float values, which is not valid according to the docstring. I think we should probably fix this in onset_detect by rounding and casting to int, but we could also fix it in peak_pick by doing the same.

Since `peak_pick` needs integer values there, i think that's the place to fix it (with a ceiling, by default).

**Comment by craffel** [comment]
> One sample for pre_max (and post_max) should still be valid though, right? Wouldn't that just correspond to a localmax?

Yep, it's valid, but it's arguably wrong because the parameter optimization was done for a different hop size.

> Since peak_pick needs integer values there, i think that's the place to fix it (with a ceiling, by default).

This is a broader question -- if the docstring/function wants input of a certain type, is it the function or caller's job to cast to that type?  If we cast to int within `peak_pick`, we should probably place input casts on all functions throughout the library (unless this is done already).

**Comment by bmcfee** [comment]
> Yep, it's valid, but it's arguably wrong because the parameter optimization was done for a different hop size.

But it shouldn't crash.  (Also, the parameter is a function of time and expressed in terms of hop_size and sr, so it should be okay, if not exactly optimal.)


> This is a broader question -- if the docstring/function wants input of a certain type, is it the function or caller's job to cast to that type?

Python, being weakly typed, generally wants you to be able to get away without casting at all.

In librosa, that doesn't exactly fly, so we do explicit checks in certain places.  (see: `util.valid_audio`, or the complex-type checks in `specshow` or `hpss`.)  We're not entirely consistent about it though, and i don't think we necessarily have to be (except where it's absolutely required).

In this specific case, I don't have any strong feelings about where type sanity should be enforced.  It might be good to throw a warning if the expected-integer values are non-integrable.

**Comment by craffel** [comment]
> But it shouldn't crash.

Right, it crashed (essentially) because the arg was non-int, not because it's a bad parameter setting.

> In this specific case, I don't have any strong feelings about where type sanity should be enforced. It might be good to throw a warning if the expected-integer values are non-integrable.

OK, so you'd suggest

```Python
if type(pre_max) != int:
    warnings.warn('Provided pre_max is non-int, using int(ceil(pre_max)) instead')
    pre_max = int(np.ceil(pre_max))
```
for all window arguments in `peak_pick`?

**Comment by bmcfee** [comment]
> OK, so you'd suggest
> 
> if type(pre_max) != int:
>     warnings.warn('Provided pre_max is non-int, using int(ceil(pre_max)) instead')
>     pre_max = int(np.ceil(pre_max))
> for all window arguments in peak_pick?

I wouldn't do an exact type equivalence test.  Instead, this might be better
```python
isinstance(pre_max, six.integer_types + (np.integer,))
```
since it would catch `int`, `long`, and numpy integer of any precision.

**Comment by craffel** [comment]
OK, updated the PR.

**Comment by bmcfee** [comment]
a7af2a9d52d208a474e05c900506e3a8f47160f9 factors that validatoin out into its own function (`util.valid_int`).

**Comment by bmcfee** [comment]
Onset detection unit tests now cover multiple hop-lengths.
