### ISSUE TITLE
"Soft" feature.sync?

### ISSUE THREAD

**Issue by craffel** [bmcfee/librosa#176]
Currently, `feature.sync` assumes that you want to integrate over frame indices, i.e. "aggregate features from frame n to frame m".  In the more general case, you have a sequence of times (call it `times`) of shape `(n_samples,)` and a series of feature vectors (call it `values`) of shape `(n_features, n_samples - 1)` where `values[:, n]` denotes the value of the features from `times[n]` to `times[n + 1]`.  In this setting, `feature.sync` can be thought of as assuming both `times` and and the times you want to aggregate over (call them `new_times`) are on the same uniform grid.  This isn't always the case; as an example, in [beat_aligned_feats](https://github.com/craffel/music-evolution/blob/master/msd/beat_aligned_feats.py) from the MSD, `times` are segment times and `new_times` are beat locations.  To aggregate, they construct a time-warp matrix and compute a dot product (similar, I think, to how `librosa` computes log frequency spectrograms).  Here's a toy example:
![unknown](https://cloud.githubusercontent.com/assets/417568/6830317/5edfe2fe-d2ef-11e4-8c7e-b791a436e72b.png)
The green lines are `times`, the blue lines are `new_times`, and the black horizontal lines are `values` (here, there's only one feature dimension).  For simplicity, the value between `times[0]` and `times[1]` is 1, between `times[1]` and `times[2]` is 2, and so on.  Using mean aggregation, after aggregating over `new_times`, the first output should be 1.8, which is `(.1*1 + .4*2)/.5` - the value over this interval is 1 for .1 time-units, 2 for .4 time-units, and the total interval length is .5 time-units.  Does that make sense?

Constructing the time warp matrix and computing the dot-product as done in `beat_aligned_feats` is inefficient; here's an implementation of what I describe above which is about 3 times faster for the beat-aligning-MSD-features task:

```Python
def soft_sync(times, values, new_times):
    '''
    Perform soft mean aggregation of `values` over the intervals in `new_times`.
    If any of `new_times` falls outside of the limit of `times`,
    the edge values are used.
    
    Parameters
    ----------
    
    times : np.ndarray [shape=(n_time_steps,)]
        Time boundaries of the original values
    
    values : np.ndarray [shape=(n_features, n_time_steps - 1)]
        `values[n]` is the feature vector from `times[n]` to `times[n + 1]`
    
    new_times : np.ndarray [shape=(n_new_time_steps,)]
        Intervals over which to aggregate `values`
    
    
    Returns
    -------
    
    new_values : np.ndarray [shape=(n_features, n_new_time_steps - 1)]
        `values` aggregated over `new_times`
    '''
    # Adjust times to span new_times, effectively using edge values
    if new_times[0] < times[0]:
        times[0] = new_times[0]
    if new_times[-1] > times[-1]:
        times[-1] = new_times[-1]
    # Find the first time after each new_time
    first_after = np.argmax(np.less.outer(new_times, times), axis=1)
    # Find the first time before each new_time
    last_before = first_after - 1
    # Add the new times to the list of times
    times = np.append(times[:-1], new_times)
    # Add the values at the new times into values
    values = np.hstack([values, values[:, last_before]])
    # Re-sort times with the new times
    time_sort = np.argsort(times)
    times = times[time_sort]
    # apply the same sorting to the values
    values = values[:, time_sort]
    # Find the indices of times equal to the new times
    equal_idx = np.argmax(np.equal.outer(new_times, times), axis=1)
    # Compute interval lengths
    lengths = np.diff(times)
    new_lengths = np.diff(new_times)
    # Aggregate over all new time intervals
    return np.array([(lengths[a:b]*values[:, a:b]/new_lengths[n]).sum(axis=1)
                     for n, (a, b)
                     in enumerate(zip(equal_idx[:-1], equal_idx[1:]))]).T
```

I think the slowest part is the last line which I can't think of a way to do without a for loop, although the `less.outer` and `equal.outer` may be inefficient too. (any ideas to make it or `beat_aligned_feats`'s version more efficient are appreciated)

Is this something that would be useful to have in `librosa`?  It should also be possible to do a weighted median instead of a weighted mean.

**Comment by bmcfee** [comment]
> the value over this interval is 1 for .1 time-units, 2 for .4 time-units, and the total interval length is .5 time-units. Does that make sense?

In the specific case of averaging, yeah, I think I get it.  It's considerably more complex for generic aggregators though: how would it work for median?  max?

I'm not sure I like the idea of having two unaligned, non-uniform index sets though (`times` vs `new_times`).  It's conceptually much more simple to push one of them down to a uniform grid (as illustrated in your figure) and then just have the one non-uniform index.  Once you've already done that, is the rest of this really necessary?


> I think the slowest part is the last line which I can't think of a way to do without a for loop, although the less.outer and equal.outer may be inefficient too.

Really?  That looks like a weighted dot product; should be pretty quick if you slice down the `lengths` and `values` vectors accordingly.  OTOH, it could also be okay to use loops and cythonize (see #157 ), if we were to actually build this out.



> Is this something that would be useful to have in librosa? It should also be possible to do a weighted median instead of a weighted mean.

I'm not totally sold on the idea.  It seems like if you're really after this level of control, you might be better off switching to a time-indexed pandas dataframe and using its timeseries interpolation functions.  In the case of MSD features, the sample size is small (ie beat-indexed not frame indexed), so it shouldn't be very expensive.

**Comment by craffel** [comment]
> In the specific case of averaging, yeah, I think I get it. It's considerably more complex for generic aggregators though: how would it work for median? max?

I don't know; right now I'm only targeting mean aggregation.

> I'm not sure I like the idea of having two unaligned, non-uniform index sets though (times vs new_times). It's conceptually much more simple to push one of them down to a uniform grid (as illustrated in your figure) and then just have the one non-uniform index. Once you've already done that, is the rest of this really necessary?

That's essentially what the code does - it resamples one time series to the times present in the other so that it can be indexed.  Unless I'm not understanding what you mean.

> Really?

Yes, confirmed via profiling.

>  That looks like a weighted dot product;

That's how `beat_aligned_feats` does it, but the way they compute the time-warp matrix for the dot-product is less efficient than what I have above.

> should be pretty quick if you slice down the lengths and values vectors accordingly.

How?

> It seems like if you're really after this level of control, you might be better off switching to a time-indexed pandas dataframe and using its timeseries interpolation functions.

I'm not familiar with `pandas` or their interpolation functions, so I don't have any intuition whether thjis would work or be faster.  The code I posted is doing a zero-order hold, which is the only interpolation needed here - it could also be done with `scipy.interpolate.interp1d` but then would have to iterate over feature dimensions (none of the >1d interpolators in scipy implement zero-order interpolation) which I was assuming would be slower.

**Comment by craffel** [comment]
I swapped out the original `align_feats` in my local `beat_aligned_feats` copy with my function from above https://github.com/craffel/midi-dataset/blob/master/beat_aligned_feats.py#L197.  Closing this, feel free to reopen if it's something you want in librosa.
