### ISSUE TITLE
Add reference for chroma_stft

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#188]
The STFT chroma implementation is based on chromagram_E from dpwe's example code.

We should add a back-reference to this in the documentation.

**Comment by dpwe** [comment]
Chroma_e was meant as a straw man, it's very blurry. Isn't chroma_p (zero
out non local maxima) better?

  DAn.

**Comment by bmcfee** [comment]
Fair point.

Looking back, I think this was actually ported indirectly by adapting from ronw's frontend package (which does not mask) and not from the matlab source.

At any rate, it would be trivial to add localmax masking as a post-processing step.  We can add this in the next minor revision (0.4.1); or if you feel it's really *really* important, we can squeeze it into 0.4.0 while @ebattenberg finishes up #172 .

**Comment by dpwe** [comment]
It's not really important.  I only think it should be better (well, we had
results in https://www.ee.columbia.edu/~dpwe/pubs/EllisP07-coversongs.pdf
but they don't quite address this point, and I have doubts about them).  It
would be interesting to actually compare the influence on some task.

  DAn.

**Comment by bmcfee** [comment]
In case anyone's dying to see the difference, here's a two-line hack to get the localmax behavior, and a visual comparison of the results:

http://nbviewer.ipython.org/gist/bmcfee/6dcb0cea0d986d51e5da

**Comment by bmcfee** [comment]
Addendum before I close this one out:

It seems to me that the relevant comparison to make would be frequency localmax vs percussive suppression (hpss) as pre-processing steps to chroma extraction.  My hunch is that localmax might handle vibrato better, but hpss will be more stable.  This all might make for a nice demo notebook...
