### ISSUE TITLE
Time signature detection?

### ISSUE THREAD

**Issue by ruohoruotsi** [bmcfee/librosa#194]
Are there any plans to implement something like this?  *Time Signature Detection by Using a Multi Resolution Audio Similarity Matrix* (http://arrow.dit.ie/cgi/viewcontent.cgi?article=1080&context=argcon)

I'm putting the finishing touches on my implementation, and because I use librosa for beat & chroma work, thought it might fit if there's nothing else planned. Cheers.

**Comment by bmcfee** [comment]
There are not currently plans to implement this, but it sounds interesting.

Depending on how specific (and effective) the implementation is, it may or may not be appropriate for inclusion in the main library.

As a side note: I've been thinking about reigning in the scope of what exactly librosa does (and should do).  I'd like to keep the core library relatively small and focused on low-level building blocks.  High-level tasks and statistical models should probably live in a separate library; something like time signature detection might be in kind of a gray area, but I'm interested in hearing other folks' opinions.

**Comment by dpwe** [comment]
> As a side note: I've been thinking about reigning in the scope of what
> exactly librosa does (and should do). I'd like to keep the core library
> relatively small and focused on low-level building blocks. High-level tasks
> and statistical models should probably live in a separate library; something
> like time signature detection might be in kind of a gray area, but I'm
> interested in hearing other folks' opinions.

I think when something works really well, and there's not variation of
opinion about how to implement it, it's a service to include it in the
library. HPSS fits this in my opinion.

But when it's something that's still very much an open research topic
with competing solutions, it seems partisan to start picking and
choosing ones to include in the library.  AFAIU time signature
detection is still in that category.

  DAn.

**Comment by bmcfee** [comment]
@dpwe well said. One caveat is that if competing solutions tend to use and combine the same components (eg, recurrence matrices) then it's useful to include these core functions.  I don't know anything about meter detection, but I suspect that there might be useful components that we're currently missing.

For the record: something like onset detection or beat tracking also fits more into the latter category than any of us would like to admit.  They're pretty fundamental to a lot of upstream representations (eg, beat-synchronous chroma), so it's useful to include even imperfect (but simple) methods for them.

**Comment by ruohoruotsi** [comment]
okay, I'll submit a pull request when I'm ready, even if its more useful as "building blocks" used by competing solutions. Great discussion on the merits, etc and great work again librosa! cheers.
