### ISSUE TITLE
decompose question frequency range.

### ISSUE THREAD

**Issue by apiszcz** [bmcfee/librosa#199]
I have a signal capture at 8KHZ so the most I can expect is ~4KHZ of frequency content. When I follow the librosa decompose example (v0.4rc2) the plot and data extends to 11025HZ. Is there a recommended parameter path either for the stft or elsewhere to only decompose to 4KHZ? Thanks.

**Comment by bmcfee** [comment]
`librosa.display.specshow` accepts a sampling rate parameter, which is used for setting axis labels.  The default is 22050 (as everywhere else in librosa), but you can override this by doing something like the following:
```python
>>> y, sr = librosa.load(librosa.util.example_audio_file(), sr=8000)
>>> D = librosa.stft(y)
>>> librosa.display.specshow(D, y_axis='log', sr=sr)
```

This works as expected on my installation.  If it's behaving differently for you, please post some example code that behaves incorrectly, and we can refile this as a bug report.

**Comment by apiszcz** [comment]
Perfect, thanks, setting sr for specshow works. I perfomed the stft, etc
with sr=8000 but not specshow.
​
