### ISSUE TITLE
Skip tests if missing data?

### ISSUE THREAD

**Issue by ebattenberg** [bmcfee/librosa#200]
I recently tried to run the unit tests from my local machine, but it looks like some of them require audio data files that aren't a part of the repo.  

Would it be a good idea to skip tests that require external data if that external data is missing?  Or is skipping tests dangerous, and we should encourage contributors to obtain the audio data themselves?

**Comment by bmcfee** [comment]
> I recently tried to run the unit tests from my local machine, but it looks like some of them require audio data files that aren't a part of the repo.

Really?  which ones?  All of the test fixtures should be in the git repo, though not in the package distribution.  Given how the whole travis setup works, I'd be surprised if there were missing fixtures.

**Comment by ebattenberg** [comment]
It just looks like there's a missing `data` top-level directory that's supposed to contain test wavs (e.g. `test1_22050.wav`).

**Comment by ebattenberg** [comment]
Oh yeah, you mentioned some Matlab script that makes the test data.

**Comment by bmcfee** [comment]
How are you running the tests?  The following ought to work:
```bash
$ nosetests -v -w tests/
```

The `data` directory lives under `tests`, and if you're in a clone of the repo, it should work.

**Comment by ebattenberg** [comment]
I see.  It looks like that works.  I was running `nosetests --with-coverage tests/` from the clone root before as is suggested in `CONTRIBUTING.md`.

I guess I needed the `-w` on there.

**Comment by bmcfee** [comment]
Derp!  Good call; I should make the contributing doc more precise.

**Comment by dawenl** [comment]
There are a couple of ``scikit-learn`` in ```CONTRIBUTING.md``` that should be replaced with ``librosa``.

**Comment by bmcfee** [comment]
Hah!  Even more embarrassing.  I'll fix this and revise the instructions.
