### ISSUE TITLE
display.waveplot efficiency rewrite

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#207]
[cc @craffel ]

The `waveplot` function could be more efficient by side-stepping the downsampling operation.  Instead, we can simply `util.frame` the signal(s) to the desired sampling rate, and use `np.max` directly on the columns (without `abs`) to get the amplitude envelope(s) in-place without copies or resampling.

**Comment by bmcfee** [comment]
fixed by #209

**Comment by craffel** [comment]
:+1:
