### ISSUE TITLE
CQT bug when hop_length != 2^k

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#208]
[paging @ebattenberg ]

When the hop isn't a power of two, the bottom octave(s) can fall out of alignment.

I came across this one while experimenting with different hop lengths in CQT.  Here's a [notebook](http://nbviewer.ipython.org/gist/bmcfee/c6aa2ab3d4823f69a4b5) to reproduce the error.

I think the error here is requiring `hop_length >= 2^k` (for `k >= num_octaves`).  Instead, 
it seems to me that the correct logic here would require hop_length to be an integer multiple of 2^k, and then require that `k >= num_octaves`.

Or perhaps there's a clever way to propagate the remainder of the hop after downsampling, rather than [flooring](https://github.com/bmcfee/librosa/blob/master/librosa/core/constantq.py#L227) as is currently done?

**Comment by ebattenberg** [comment]
> I think the error here is requiring hop_length >= 2^k (for k >= num_octaves). Instead, 
> it seems to me that the correct logic here would require hop_length to be an integer multiple of 2^k, and then require that k >= num_octaves.

I think that sounds like a reasonable way to deal with it in the short term.  We definitely want to ensure that the initial hop_length can be evenly divided by two as many times as we need to.

**Comment by ebattenberg** [comment]
There's also the option of round the input hop_length to the nearest integer that satisfies the above constraint, but that may produce unexpected results for the user who is expecting a specific hop size.  Maybe issue a warning when the criteria isn't met and do then do the rounding?  Though, I think raising a `ValueError` with a helpful message (maybe suggested nearby values of `hop_length` --both above and below the requested value-- that meet the criteria) is probably the best way to go.

**Comment by bmcfee** [comment]
> There's also the option of rounding the input hop_length to the nearest integer that satisfies the above constraint, but that may produce unexpected results for the user who is expecting a specific hop size.

Exactly.  I'd prefer to not change hops, so that we can guarantee that different analyses with the same hop length and sampling rate stay aligned.



> Though, I think raising a ValueError with a helpful message (maybe nearby values of hop_length --both above and below the requested value-- that meet the criteria) is probably the best way to go.

Agreed.  I'll make the PR later today.

**Comment by bmcfee** [comment]
Another source of error here is the that rounding errors cascade by the recursive division.  We could get maybe a little more precision out of dividing the original hop by `2**k` instead of doing it dynamically, but I'm not sure if this would introduce jaggies or screw things up in the early downsampler.

**Comment by ebattenberg** [comment]
Another issue is that the actual number of times we downsample could be more than the number of octaves if early downsampling comes into play.

**Comment by ebattenberg** [comment]
Maybe we should issue a warning whenever the current `hop_length` doesn't evenly divide whenever we downsample.  That way, we'll at least be aware of all the possible ways this problem could occur.  Then we could address them (e.g., don't do early downsampling if it wouldn't allow the even division of the hop length at a later time.)

**Comment by ebattenberg** [comment]
Also, when we do two octaves of filters before downsampling, we need the `hop_length` to support one fewer octave.
