### ISSUE TITLE
audioread dependency?

### ISSUE THREAD

**Issue by conormdurkan** [bmcfee/librosa#212]
I'm using Conda to install librosa from [here](https://binstar.org/HCC/librosa), and even though I've got audioread installed, it gives me a missing dependency error. Any ideas?

**Comment by bmcfee** [comment]
Can you post a log of the error message?  It's generally difficult to debug without at least that much.

A couple of additional things:

* I don't maintain the conda channel you're using, and don't know the person that does.
* The librosa on the conda channel is outdated.  You probably should upgrade to 0.4.0 via pip.
* All else being equal, it sounds like your problem stems from audioread, not librosa.  You should probably make sure that audioread works first, and take care of any codec dependencies (eg, ffmpeg) before moving on to testing librosa.

**Comment by bmcfee** [comment]
Since this issue stems from audioread and not librosa, I think there's nothing for us to do here.
