### ISSUE TITLE
Enhancement: Add an audio marker to onsets like essentia.standard.AudioOnsetsMarker

### ISSUE THREAD

**Issue by stevetjoa** [bmcfee/librosa#216]
Essentia has this handy feature, [AudioOnsetsMarker](http://essentia.upf.edu/documentation/reference/std_AudioOnsetsMarker.html), which adds a beep to the location of each onset. I've found the auditory cue as helpful as the visual cue, if not more so, for assessing the correctness of onsets.

For example, see the last cell of [this IPython notebook](http://musicinformationretrieval.com/onset_detection.html).

Perhaps it might look something like:

    onset_frames = librosa.onset.onset_detect(x, fs)
    x_with_beeps = librosa.onset.onset_marker(x, onset_frames)

**Comment by bmcfee** [comment]
This function is already implemented in [`mir_eval`](https://github.com/craffel/mir_eval/blob/master/mir_eval/sonify.py#L11), but we can certainly duplicate it here.

**Comment by stevetjoa** [comment]
Ah sorry about that, I do see that now in `mir_eval`. Feel free to resolve as you wish. Perhaps a more prominent example in the docs might help (in which I can definitely contribute).

**Comment by bmcfee** [comment]
Well, I think you're right that this is a useful feature to have, and its utility isn't limited to evaluation, so it makes sense to include some version of it in librosa.

I'd like to generalize the interface a bit in a couple of ways:
- supply beep marker locations in time or in frames
- have a user-specified beep frequency

**Comment by stevetjoa** [comment]
I'd be happy to submit a pull request for that. Where do you think it should live, e.g. `librosa.sonify.clicks`, or `librosa.display.clicks`, or `librosa.eval.clicks`, etc.?

**Comment by bmcfee** [comment]
Good question.  I'd rather not add a separate submodule just for one function, but none of the existing ones really seem appropriate either.

Maybe it can go in some submodule of `core` and just be `librosa.clicks`?  What do other folks think?

**Comment by stevetjoa** [comment]
Just noticed that you implemented this thanks to a talk last night by Colin. Thanks!
