### ISSUE TITLE
No Backends

### ISSUE THREAD

**Issue by dsiah** [bmcfee/librosa#219]
When running the example I receive this error
```
In[2]:

import matplotlib, librosa
In [3]:

import IPython.display
import numpy as np
In [4]:

import matplotlib.pyplot as plt
%matplotlib inline
In [12]:

y, sr = librosa.load(librosa.util.example_audio_file())
---------------------------------------------------------------------------
NoBackendError                            Traceback (most recent call last)
<ipython-input-12-1c3f0c525dc9> in <module>()
----> 1 y, sr = librosa.load(librosa.util.example_audio_file())

/Library/Python/2.7/site-packages/librosa/core/audio.pyc in load(path, sr, mono, offset, duration, dtype)
    106 
    107     y = []
--> 108     with audioread.audio_open(os.path.realpath(path)) as input_file:
    109         sr_native = input_file.samplerate
    110 

/Library/Python/2.7/site-packages/audioread/__init__.pyc in audio_open(path)
     94 
     95     # All backends failed!
---> 96     raise NoBackendError()

NoBackendError: 
```

Any Ideas as to what could be causing this? I am running the example in Ipython notebook and OSX Yosemite 10.10

**Comment by bmcfee** [comment]
Were you able to resolve this?

I suspect the problem is a missing ogg vorbis codec for audioread.  Installing ffmpeg or gstreamer (with plugins) should fix this for you.

.wav files should work out of the box, but we don't ship the demo track in wav.

**Comment by dsiah** [comment]
I tried ffmpeg which resulted in python hanging when I try to load that sample Ogg file. I will experiment and see if I can fix it, but the reason for failure must  have been that codec.

I will avoid or convert files that I am analyzing from ogg for now.

**Comment by bmcfee** [comment]
> I tried ffmpeg which resulted in python hanging when I try to load that sample Ogg file.

That may just be resample being slow, rather than hanging.  What happens if you do:

```python
>>> y, sr = librosa.load(librosa.util.example_audio_file(), duration=5.0)
```
?

**Comment by dsiah** [comment]
Success :+1: thank you.

**Comment by stefan-balke** [comment]
@dsiah go and get libsamplerate.

The easiest way is to do it by
`brew install libsamplerate`
Afterwards you need to install
`pip install scikits.samplerate`

**Comment by macramole** [comment]
The solution for ubuntu based systems is:
sudo apt-get install libav-tools

**Comment by gongqiang** [comment]
@macramole  omg, you solved a big problem for me ,dude, you are the GOAT!

**Comment by thomashzhang** [comment]
Any ideas how I fix this error on Windows? I'm unsure what to do with ffmpeg once I downloaded it nor do I understand what the vorbis codec is.

I'm unsure if it's even the same error.
![capture](https://user-images.githubusercontent.com/2775684/33308786-c5391cde-d3d0-11e7-9999-992d2f928c09.PNG)

**Comment by bmcfee** [comment]
@thomashzhang that's an entirely different error with vamp/melodia, and not related to librosa.

**Comment by davidglavas** [comment]
I'm using windows and solved this by setting up ffmpeg as shown [here](https://www.youtube.com/watch?v=xcdTIDHm4KM) and restarting my IDE.

**Comment by nathneel** [comment]
Could anyone help me with this?
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\neel.nath\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\externals\loky\process_executor.py", line 398, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\neel.nath\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\_parallel_backends.py", line 561, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\neel.nath\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\parallel.py", line 224, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\neel.nath\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\parallel.py", line 224, in <listcomp>
    for func, args, kwargs in self.items]
  File "<timed exec>", line 6, in save_folds
  File "<ipython-input-24-be5fe47a6f6e>", line 15, in extract_features
  File "<ipython-input-23-78f52d60a917>", line 4, in read_audio
  File "C:\Users\neel.nath\AppData\Local\Programs\Python\Python36\Lib\site-packages\librosa\core\audio.py", line 112, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "C:\Users\neel.nath\AppData\Local\Programs\Python\Python36\Lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError
"""

The above exception was the direct cause of the following exception:

NoBackendError                            Traceback (most recent call last)
<timed exec> in <module>()

~\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\parallel.py in __call__(self, iterable)
    960 
    961             with self._backend.retrieval_context():
--> 962                 self.retrieve()
    963             # Make sure that we get a last message telling us we are done
    964             elapsed_time = time.time() - self._start_time

~\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\parallel.py in retrieve(self)
    863             try:
    864                 if getattr(self._backend, 'supports_timeout', False):
--> 865                     self._output.extend(job.get(timeout=self.timeout))
    866                 else:
    867                     self._output.extend(job.get())

~\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
    513         AsyncResults.get from multiprocessing."""
    514         try:
--> 515             return future.result(timeout=timeout)
    516         except LokyTimeoutError:
    517             raise TimeoutError()

~\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\externals\loky\_base.py in result(self, timeout)
    429                 raise CancelledError()
    430             elif self._state == FINISHED:
--> 431                 return self.__get_result()
    432             else:
    433                 raise TimeoutError()

~\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\externals\loky\_base.py in __get_result(self)
    380     def __get_result(self):
    381         if self._exception:
--> 382             raise self._exception
    383         else:
    384             return self._result

NoBackendError:

**Comment by fdjingyuan** [comment]
you may try this if you have conda:

conda install -c conda-forge librosa

**Comment by Shashank-Mittal** [comment]
![image](https://user-images.githubusercontent.com/39668339/46251996-502fca00-c47f-11e8-8dd1-ad9a6a495596.png)

**Comment by KimMeen** [comment]
I met the same issue, and I use this command to solve the problem: `conda install ffmpeg -c conda-forge`
My environment is Windows7 with Anaconda.

**Comment by stephen-song** [comment]
i solved this problem by adding one line code 
`envdir_list.append('C:/ffmpeg/bin')`
in pydub.utils.py  def which(program)

**Comment by ejlok1** [comment]
Hi all. Abit late to this but strangely enough what I found worked amazingly without installing FFMPEG, is to install Imagemagick. https://imagemagick.org/script/index.php

imagemagick from its windows installer comes with a ffmpeg.exe, and after installing, imagemagick automatically adds the file path to the environment variables. So unintentionally, this seems to worked well!

**Comment by ignafusion** [comment]
Hi all, i have some question from my code. why this code is not running ?

`import librosa
audio_path = 'jakarta1.wav'

x , sr = librosa.load(audio_path)
`
and this is the error message

`---------------------------------------------------------------------------
NoBackendError                            Traceback (most recent call last)
<ipython-input-1-32a6738b8bfc> in <module>
      2 audio_path = 'jakarta1.wav'
      3 
----> 4 x , sr = librosa.load(audio_path)
      5 

~\Anaconda3\envs\ujicoba\lib\site-packages\librosa\core\audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    110 
    111     y = []
--> 112     with audioread.audio_open(os.path.realpath(path)) as input_file:
    113         sr_native = input_file.samplerate
    114         n_channels = input_file.channels

~\Anaconda3\envs\ujicoba\lib\site-packages\audioread\__init__.py in audio_open(path)
    114 
    115     # All backends failed!
--> 116     raise NoBackendError()

NoBackendError: 
`

**Comment by anindya-sadhukhan** [comment]
NoBackendError                            Traceback (most recent call last)
<ipython-input-148-044474756f5c> in <module>
      3 for index,y in enumerate(mylist):
      4     if mylist[index][6:-16]!='01' and mylist[index][6:-16]!='07' and mylist[index][6:-16]!='08' and mylist[index][:2]!='su' and mylist[index][:1]!='n' and mylist[index][:1]!='d':
----> 5         X, sample_rate = librosa.load('aud/'+y, res_type='kaiser_fast',duration=3,sr=22050*2,offset=0.5)
      6         sample_rate = np.array(sample_rate)
      7         mfccs = np.mean(librosa.feature.mfcc(y=X,sr=sample_rate, n_mfcc=13),axis=0)

/anaconda3/lib/python3.6/site-packages/librosa/core/audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    117 
    118     y = []
--> 119     with audioread.audio_open(os.path.realpath(path)) as input_file:
    120         sr_native = input_file.samplerate
    121         n_channels = input_file.channels

/anaconda3/lib/python3.6/site-packages/audioread/__init__.py in audio_open(path)
    114 
    115     # All backends failed!
--> 116     raise NoBackendError()

NoBackendError: 
 how do I solve this , I tried installing all related modules but still it is not working.

**Comment by lostanlen** [comment]
@anindya-sadhukhan what's `path`?

**Comment by a-venug** [comment]
Using Anaconda on Windows 10...Installed ffmpeg...still getting the same error.Anyone??

**Comment by lostanlen** [comment]
@a-venu Hello, please please make sure you activate the environment with `source activate`
Make sure you install librosa in this environment (`conda install -c conda-forge librosa`) 
The UNIX command `which python` should return a path in the miniconda path, not system Python.
Then call `python`, `import librosa`, and `load` the example file.
I hope this helps!

**Comment by a-venu** [comment]
@lostanlen Hi, I installed librosa and ffmpeg  inside my tensorflow environment in Anaconda.
Still same error
![2019-03-07 3](https://user-images.githubusercontent.com/32105115/53957798-5482a200-4105-11e9-9c58-c79233a16a5e.png)

**Comment by anindya-sadhukhan** [comment]
> @anindya-sadhukhan what's `path`?

I'm using Mac, which path.?

**Comment by stefan-balke** [comment]
Open a terminal and enter `echo $PATH`, copy the output, and paste it here.

**Comment by debjitk99** [comment]
> > I tried ffmpeg which resulted in python hanging when I try to load that sample Ogg file.
> 
> That may just be resample being slow, rather than hanging. What happens if you do:
> 
> ```python
> >>> y, sr = librosa.load(librosa.util.example_audio_file(), duration=5.0)
> ```
> 
> ?

i have same problem with librosa but now its solve but now its now showing any output

**Comment by zohaibmushtaq** [comment]
I am sure this command will work to install ffmpeg and then there will be no backend error

"sudo apt  install ffmpeg"
if it works then please thumbs up if not then sorry.

**Comment by giacaglia** [comment]
I'm seeing the same problem with an audio file, even after installing ffmpeg and other libraries. :-(

**Comment by Vichoko** [comment]
Fixed in Ubuntu 18 by` sudo apt-get install ffmpeg`

**Comment by hadpro24** [comment]
sudo apt-get install ffmpeg : fix my problem Ubuntu 20
