### ISSUE TITLE
How to write wav file of PCM format?

### ISSUE THREAD

**Issue by friskit-china** [bmcfee/librosa#223]
Hello,

Recently, I need librosa to process some audio file. When I use "librosa.out.write_wav()", I got a wav file with format of "WAVE_FORMAT_IEEE_FLOAT". But I need the format of "WAVE_FORMAT_PCM".

Could you please tell me how to do that?

(sorry, I'm not good in English)

**Comment by friskit-china** [comment]
I find a way to do that.

Use pysndfile which provide a lot of ways to save wav file.

for example
```
pysndfile.sndio.write('somewave.wav', output_istft, rate=16000, format='wav', enc='pcm16')
```

**Comment by dpwe** [comment]
Is that on purpose, the WAVE_FORMAT_IEEE_FLOAT thing?  It strikes me as the
opposite of useful.

"But it avoids having to address the issue of scaling and/or clipping."

"Your majesty is like a dose of clap."

  DAn.

**Comment by bmcfee** [comment]
> Does any one have the better solution?

Nope!  You beat me to the punch, but I'd recommend using pysoundfile if you want maximal control over the encoding of your output.

The librosa.output function is just a convenience wrapper for scipy's wav writer, so any odd behavior is up to scipy, not librosa.
