### ISSUE TITLE
RuntimeWarning in pitch.py

### ISSUE THREAD

**Issue by rabitt** [bmcfee/librosa#233]
I'm running into divide by zero warnings periodically while running [this script](https://github.com/bmcfee/laplacian_segmentation/blob/master/code/segmenter.py) in batch

[This line](https://github.com/bmcfee/librosa/blob/master/librosa/core/pitch.py#L249), this error:
```RuntimeWarning: divide by zero encountered in divide
shift = avg / (shift + (shift < util.SMALL_FLOAT))```

**Comment by bmcfee** [comment]
That's pretty strange: the clipping there should be enough to avoid div-by-zeros.  @craffel care to chime in?

@rabitt can you provide an example clip that triggers this, or at least a traceback?  I suppose it's coming from tuning estimation in CQT, but it would help to know what exactly the signal is.

**Comment by rabitt** [comment]
this is all I've got for you :disappointed: : 
```[1/5] loading audio```
```[2/5] Separating harmonic and percussive signals```
```[3/5] detecting beats```
```[4/5] generating CQT```
```/usr/local/lib/python2.7/site-packages/librosa/core/pitch.py:249: RuntimeWarning: divide by zero encountered in divide
  shift = avg / (shift + (shift < util.SMALL_FLOAT))```

@bmcfee: Re example clip - I would if I could :(

**Comment by bmcfee** [comment]
Sounds like you get to go hacking around the guts of piptrack!

I'd recommend saving off `S`, `avg`, and `shift` matrices for offline probing (prior to that line).

I wonder if it's something like `SMALL_FLOAT < shift < division underflow threshold`.  That shouldn't happen, in any sane universe, but it's the only thing that makes sense.

Alternately, you could try raising `SMALL_FLOAT` until the warning goes away, and then hunt for `shift` values in that neighborhood.

**Comment by craffel** [comment]
This has happened to me too!  In a similar setting - computing CQTs (and therefore lots of tuning estimations) for lots and lots of audio files.  I went digging around for a minute and concluded that the universe wasn't sane, and then proceeded to ignore it.  I am all out cores to debug this at the moment, though. If I see it again, I will be more diligent.

**Comment by bmcfee** [comment]
Aha! This can happen if `shift==-1`, so that `shift + (shift < util.SMALL_FLOAT)` cancels out.

From what I can tell, there's no reason that `shift` can't be negative in general, so that threshold test is incorrect, and should probably be replaced by `shift + (np.abs(shift) < util.SMALL_FLOAT)`.

@rabitt can you test that change out, and if it works, submit a PR?

**Comment by rabitt** [comment]
@bmcfee sure, will try it out tomorrow first thing

**Comment by bmcfee** [comment]
side note: this becomes easier to catch after `np.seterr(divide='warn')`.
