### ISSUE TITLE
Usage of piptrack

### ISSUE THREAD

**Issue by smasfara** [bmcfee/librosa#244]
Hi,

I'am trying to use librosa.core.piptrack.
librosa.core.piptrack(y), with y an audio file of approximately 255s gives me an output of an array with shape (2049,5637) with default sampling rate.
I thought 5637 was the number of frames in the file but librosa.core.frames_to_time(5367)=130s
What am I missing?

**Comment by bmcfee** [comment]
Good catch!

When the input is a waveform, `piptrack` uses a default `n_fft=4096` and then infers `hop_length=1024`, so the hop does not match up to the default parameters in `frames_to_time`.

If you explicitly set the frame and hop lengths, everything should line up as you expect.

This, to me, looks like a mistake on our end in that we missed standardizing the defaults for `piptrack`.  I'll make an issue to fix this in the next minor revision.

**Comment by bmcfee** [comment]
Just a quick update: PR #246 fixes this and has been merged.

**Comment by smasfara** [comment]
It works perfectly now! Thanks for your quick reply!
