### ISSUE TITLE
input_file closed in librosa.core.audio.load() - Ubuntu 14.04 

### ISSUE THREAD

**Issue by wangsix** [bmcfee/librosa#254]
When loading mp3 files with `librosa.core.audio.load()`, sometimes there are some files throwing attribute errors in line 153 in audio.py, 

`AttributeError: 'MadAudioFile' object has no attribute 'mf''`. 

I checked my audioread and librosa version. Both are up-to-date. I dig further into the code and indent one level the code from line 150 to line 165 in audio.py so that input_file is not closed(?). So far this hack solved my problem (it is still running on a dataset so not sure if it is really solved or some other errors will occur). 

Any thoughts or things I should check/upgrade to avoid doing this hack?

**Comment by bmcfee** [comment]
Aha, good catch!  Indeed, we're using `input_file` outside of its context scope [here](https://github.com/bmcfee/librosa/blob/master/librosa/core/audio.py#L153).

This could make sense if audioread is  tearing down the `MadAudioFile` object after its context exits.  It's a bit strange that I don't see this error on other backends, and it makes me suspect that some audioread backends can leak state unintentionally.

I'll fix it here, but it's worth following up with the audioread devs to see why this doesn't happen on all backends.

**Comment by wangsix** [comment]
Thanks for the quick response. When I run the codes on my Mac with the mp3s there were no errors (mp3s from SALAMI internet archive). The errors only happened when I ran the same codes on a linux machine which processed all the Beatles mp3 (isophonic) but failed on some of the mp3s from SALAMI internet archive.

**Comment by bmcfee** [comment]
> The errors only happened when I ran the same codes on a linux machine which processed all the Beatles mp3 (isophonic) but failed on some of the mp3s from SALAMI internet archive.

Yeah, because the two environments are using different backends, which audioread is hiding from librosa (and you).  If you want to be a good citizen ( :smile: ), I'd suggest constructing a minimal example that demonstrates the behavior (without librosa) and report it to https://github.com/sampsyo/audioread along with the corresponding codecs in the two environments, which you can pull by calling `audioread._ca_available()`, `._gst_available()`, and `._mad_available()`.

**Comment by wangsix** [comment]
Thank you!! Gonna try to be a good citizen then.

**Comment by bmcfee** [comment]
Fixed by merging #255
