### ISSUE TITLE
Add link to the paper of librosa to the docs or README (or both)

### ISSUE THREAD

**Issue by r9y9** [bmcfee/librosa#259]
librosa is great, but I once wondered that what is the goal and what is the design principles behind librosa. 

I found this paper https://bmcfee.github.io/papers/scipy2015_librosa.pdf is really useful to understand the design principles. I think it would be great to add link to the paper to the docs or README (or both).

**Comment by bmcfee** [comment]
Good call.  The scipy proceedings hadn't been released until after the 0.4 release, but we can include the link in 0.4.1.

**Comment by r9y9** [comment]
Thanks!
