### ISSUE TITLE
Problem running Python notebooks on the example datasets

### ISSUE THREAD

**Issue by kohaugustine** [bmcfee/librosa#261]
Hi all,

I just cloned the entire repo onto my machine, and when I opened the notebooks and tried running them on the example datasets just as they are, I got the following error:

---------------------------------------------------------------------------
NoBackendError                            Traceback (most recent call last)
<ipython-input-3-f32994730795> in <module>()
      5 # audio_path = '/path/to/your/favorite/song.mp3'
      6 
----> 7 y, sr = librosa.load(audio_path)

/users/kohaugustine/continuum_miniconda/miniconda/lib/python2.7/site-packages/librosa/core/audio.pyc in load(path, sr, mono, offset, duration, dtype)
    106 
    107     y = []
--> 108     with audioread.audio_open(os.path.realpath(path)) as input_file:
    109         sr_native = input_file.samplerate
    110 

/users/kohaugustine/continuum_miniconda/miniconda/lib/python2.7/site-packages/audioread/__init__.pyc in audio_open(path)
     94 
     95     # All backends failed!
---> 96     raise NoBackendError()

NoBackendError: 

Is there anything that I could be doing wrong here?

Thank you.

**Comment by bmcfee** [comment]
Please see [this issue](https://github.com/bmcfee/librosa/issues/219).  The summary is that you're missing the necessary audio codecs for audioread to work.

**Comment by kohaugustine** [comment]
@bmcfee  Thank you for your prompt response! I will take a look at the post you directed me to.
