### ISSUE TITLE
Could not import scikits.samplerate

### ISSUE THREAD

**Issue by varun0007** [bmcfee/librosa#270]
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
In[2]: import librosa
/usr/local/lib/python2.7/dist-packages/librosa-0.4.1-py2.7.egg/librosa/core/audio.py:37: UserWarning: Could not import scikits.samplerate. Falling back to scipy.signal
Backend TkAgg is interactive backend. Turning interactive mode on.
/usr/lib/pymodules/python2.7/matplotlib/rcsetup.py:378: UserWarning: tk.pythoninspect is obsolete, and has no effect
  warnings.warn("tk.pythoninspect is obsolete, and has no effect")
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2820, in run_code
    exec code_obj in self.user_global_ns, self.user_ns
  File "<ipython-input-2-6ce83e78f094>", line 1, in <module>
    import librosa
  File "/home/varun/Desktop/pycharm-community-4.5.4/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/librosa/__init__.py", line 18, in <module>
  File "/home/varun/Desktop/pycharm-community-4.5.4/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/librosa/display.py", line 29, in <module>
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 358, in _reconstruct
    y[key] = value
  File "/usr/lib/pymodules/python2.7/matplotlib/__init__.py", line 808, in __setitem__
    cval = self.validate[key](val)
  File "/usr/lib/pymodules/python2.7/matplotlib/rcsetup.py", line 95, in validate_bool_maybe_none
    raise ValueError('Could not convert "%s" to boolean' % b)
ValueError: Could not convert "None" to boolean

**Comment by bmcfee** [comment]
This is not a librosa error: the samplerate line is a warning, and librosa will function fine (albeit more slowly) without it.

It looks like your actual error is due to a problem in matplotlib.

**Comment by bwhitman** [comment]
This happens to me on OS X 10.10 default python install, and it is this issue of matplotlib (fixed in later versions) https://github.com/matplotlib/matplotlib/issues/2543/

The only way to get master to run on OS X default python without upgrading system matlplotlib (a huge PITA) is to change 

```
index ce7924f..c6456ae 100644
--- a/librosa/display.py
+++ b/librosa/display.py
@@ -30,7 +30,7 @@ try:
     import seaborn as sns
     _HAS_SEABORN = True
     mpl.rcParams.update(**_matplotlibrc)
-except ImportError:
+except (ImportError, ValueError):
     pass
```

**Comment by bmcfee** [comment]
Oh strange.  What version of matplotlib does it fail on?

**Comment by bwhitman** [comment]
1.3.1

**Comment by bmcfee** [comment]
Thanks.  I'll add a version requirement (>=1.4.3 most likely) on the next minor revision.

**Comment by bwhitman** [comment]
(That'll make librosa super super hard to run on a mac, perhaps a better way to do this is to just not have plotting enabled if we can't import it?)

**Comment by bmcfee** [comment]
My $0.02 is that using (apple's) native python distro is a losing proposition no matter what, and you'd be much better off switching to anaconda.

**Comment by stefan-balke** [comment]
Yap, or installing and linking it manually with homebrew. Maybe there should be something in the readme about this. Although it shouldn't describe how you can run python on a mac...

**Comment by bmcfee** [comment]
The mpl version requirement was added by merging #274 .  Otherwise, I'm not sure there's much to be done on this issue.

Since I don't have a mac, I'm not in a position to write specific documentation for getting it running.  However, if anyone feels like sending a PR for improving install instructions in the documentation, I'd be happy to include it.
