### ISSUE TITLE
I try to do tutorial but can't run it. Can someone help me? 

### ISSUE THREAD

**Issue by spk921** [bmcfee/librosa#275]
This is my code. test.py
<img width="496" alt="screen shot 2015-11-03 at 4 51 04 am" src="https://cloud.githubusercontent.com/assets/13938697/10905162/8ad551c2-81e6-11e5-96c8-ff6353c77706.png">

I run like : python test.py 
From the tutorial page it said like this : 
 The example is encoded in OGG Vorbis format, so you will need the appropriate codec installed for audioread.
However, I pip install audioread, and succeed. How can I run the tutorial? 

Below is the error messages. 

<img width="561" alt="screen shot 2015-11-03 at 4 49 23 am" src="https://cloud.githubusercontent.com/assets/13938697/10905148/66c6fe20-81e6-11e5-9cc6-abca3a517886.png">

**Comment by bmcfee** [comment]
Please refer to the discussion of issue #219 .
