### ISSUE TITLE
Better installation instructions

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#276]
Since the same issues keep popping up again and again ( #270 #275 #219 #261 ), it seems like we must have some shortcomings in the documentation.

In particular, the following points should be addressed explicitly:

- audioread backends
- scikit-samplerate
- general installation issues on osx / pointers to anaconda install instructions

Does anyone out there, preferably a mac user with direct experience, want to chip in on this?

**Comment by stefan-balke** [comment]
Yes, I will take care of the OS X part.

**Comment by bmcfee** [comment]
Awesome, thanks!

**Comment by stefan-balke** [comment]
FYI:
A colleague uses Windows + Anaconda.
scikits.samplerate ist available as a wheel from this site:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#scikits.samplerate

So the last thing to handle is now how to read compressed audio files
under windows to integrate libsndfile.

**Comment by bmcfee** [comment]
Cool, thanks for looking into that.

Do you know if that wheel supports python 3?  I've had difficulties with the main distribution of scikits.samplerate, and wouldn't be surprised if that conda channel doesn't quite work.  (FWIW, I maintain a fork-of-a-fork that works on py3 to enable testing on travis.)

**Comment by stefan-balke** [comment]
> Do you know if that wheel supports python 3?

Only tested it on Python 2.7
