### ISSUE TITLE
display.frequency_ticks

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#291]
Following the discussion [here](https://groups.google.com/forum/#!topic/librosa/dkJzIo_yydA): we should have logic to specify (and automatically determine) the units on frequency axes: mHz, Hz, KHz, MHz, GHz?

**Comment by drepetto** [comment]
I think those four are sufficient. I guess the trick will be figuring out which range is appropriate. It's common to see labels in the 1000s of mHz range. It's similar to the situation with current measurements in Amps, where a power supply will say 1500 mA. So I'm not sure how to judge when to bump up to the next range. Maybe an optional flag specifying a specific unit?

**Comment by bmcfee** [comment]
> Maybe an optional flag specifying a specific unit?

Sure; I'd probably do something like ``time_ticks()`` and have ``fmt in [None, 'mHz', 'Hz' ...]`` with ``None` corresponding to automatic scaling.

As for range boundaries, how about:
* [0, 10Hz) -> mHz
* [10Hz, 10KHz) -> Hz
* [10KHz, 10MHz) -> KHz
* [10MHz, 10GHz) -> MHz
* [10GHz, infty) -> GHz?

**Comment by drepetto** [comment]
Sure, those look like reasonable ranges. I doubt anyone would use,
say, 7000hHz, but 1500hMz is reasonable. So at the low end I'd
probably end up setting units explicitly most of the time. But those
look like good defaults.

.d

**Comment by bmcfee** [comment]
hHz? :)

One more question: would it be preferable to have all ticks on the same unit scale, or append the unit to each tick?

The former appeals to my sense of consistency.

The latter would be much more useful when working on log-frequency axes (as I usually do).

I'd rather not support both if we don't have to, since the interface could easily get too complicated.

**Comment by drepetto** [comment]
Sorry, mHz!

Yes, one unit per axis makes most sense to me. Maybe switching to
scientific notation where it makes sense, like a num_zeroes
threshold...

.d

**Comment by stefan-balke** [comment]
Just a remark:

KHz
should be

kHz. Here is a list: https://en.wikipedia.org/wiki/Hertz

**Comment by bmcfee** [comment]
> KHz should be kHz.

:+1:
