### ISSUE TITLE
Automatically install scikits.samplerate and libsamplerate

### ISSUE THREAD

**Issue by dela3499** [bmcfee/librosa#292]
Installing scikits.samplerate and libsamplerate is error-prone and time-consuming (for me). Would it be reasonable to automatically install these (admittedly optional) dependencies? It would be really great to hit the ground running (quickly) after just a pip install.

**Comment by bmcfee** [comment]
This is semi-redundant with #202.  The biggest hurdle here is that libsamplerate is not written in python, and thus cannot be used to satisfy pip dependencies.  There's no way to automate this within pip, but it's possible within conda.
