### ISSUE TITLE
hpss only mono output?

### ISSUE THREAD

**Issue by dankorg** [bmcfee/librosa#293]
Hi,

I enjoy your librosa python code so far and have the latest version, however I noticed some problem with the output.

I ran the hpss code from here:
https://github.com/bmcfee/librosa/blob/master/examples/hpss.py

and used a sample stereo file 44.1kHz sampling rate. Output works, but in mono,
how can hpss save it in stereo or is this not possible yet? Let me know, maybe by including a modified code, and thanks for your time!

Best regards,
Daniel

**Comment by bmcfee** [comment]
Hi Daniel,

This sort of question is perhaps better suited to the [discussion group](https://groups.google.com/forum/#!forum/librosa), but the short answer is that librosa is primarily designed to analyze monophonic signals.

It shouldn't be difficult to modify the hpss script with a helper function along the lines of:
```python
def stereo_hpss(y):
   if y.ndim > 1:
     yh1, yp1 = librosa.effects.hpss(y[0])
     yh2, yp2 = librosa.effects.hpss(y[1])
     return np.vstack([yh1, yh2]), np.vstack([yp1, yp2])
  else:
    return librosa.effects.hpss(y)
```
and loading the waveform with `mono=False`.

That will perform hpss independently on each channel, and then re-combine the results into stereo waveforms.
