### ISSUE TITLE
specshow y_axis='log' truncates x axis

### ISSUE THREAD

**Issue by kylemcdonald** [bmcfee/librosa#315]
When using `specshow` with `y_axis='log'`, the last bin on the x axis is chopped in half. This isn't a problem for spectra, which are generally pretty long on the x axis and a half-truncation doesn't amount to much, but I noticed it when working with the components returned by `decompose`.

```python
n=3
plt.subplot(131)
plt.title('log')
librosa.display.specshow(logamp[:,:n], y_axis='log')
plt.subplot(133)
plt.title('linear')
librosa.display.specshow(logamp[:,:n], y_axis='linear')
plt.show()
```

![wvqispvnr1uvaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/157106/14163982/12c39dc6-f6c9-11e5-8d2c-e25c75ed143e.png)

Edit: A more precise inspection reveals that this is a little weirder, the second-to-last bin is stretched to 1.5x and the last bin is squashed to 0.5x. Here's an example with `n=5`:

![hmbrppvlkxqaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/157106/14164015/6ec2c4bc-f6c9-11e5-94dc-2a260475507c.png)

**Comment by bmcfee** [comment]
Dang, I thought that had been fixed.

For the record, what version of matplotlib do you have?

Also, do you see the same behavior if you also set the `x_axis` parameter?

**Comment by kylemcdonald** [comment]
Setting `x_axis` does not help, and is actually worse with `tempo`. Strangely, setting the `x_axis='log'` (which is invalid or not documented) fixes it, but adds useless labels. Other invalid settings cause an error.

```
print matplotlib.__version__
n=4
plt.figure(figsize=(14,3))
plt.subplot(191), plt.title('log')
librosa.display.specshow(logamp[:,:n], y_axis='log', x_axis='log')
plt.subplot(193), plt.title('time')
librosa.display.specshow(logamp[:,:n], y_axis='log', x_axis='time')
plt.subplot(195), plt.title('lag')
librosa.display.specshow(logamp[:,:n], y_axis='log', x_axis='lag')
plt.subplot(197), plt.title('frames')
librosa.display.specshow(logamp[:,:n], y_axis='log', x_axis='frames')
plt.subplot(199), plt.title('tempo')
librosa.display.specshow(logamp[:,:n], y_axis='log', x_axis='tempo')
plt.show()
```

```
1.5.1
```

![wnru48zgdkyaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/157106/14182270/8d069d58-f738-11e5-91be-feafad574d68.png)

**Comment by bmcfee** [comment]
> Setting x_axis does not help, and is actually worse with tempo.

That's pretty weird -- tempo should only affect the label positions, not the rendering scale.



> Strangely, setting the x_axis='log' (which is invalid or not documented) fixes it, but adds useless labels.

All axis values are valid for either x or y_axis, eg, if you wanted to draw a spectrogram sideways for some reason, you could. Maybe this is unclear in the documentation.  Any suggestions on how to make it clear?


At any rate, I think this all comes down to edge effects and the way that matplotlib center-aligns image pixels, rather than edge alignment.  I'll do some digging into this to see if there's an easy fix.

**Comment by kylemcdonald** [comment]
> Maybe this is unclear in the documentation. Any suggestions on how to make it clear?

I checked the documentation again, and I think it's just poor reading on my part. I read "Frequency types" as "y-axis" and "Time types" as "x-axis", but at the top it clearly states "Range for the x- and y-axes."

**Comment by bmcfee** [comment]
@kylemcdonald can you check out PR #316 and let me know if this resolves the issue for you?

**Comment by kylemcdonald** [comment]
woo! #316 solves this issue for me. here's a self-contained bit of test code in case anyone else runs into the same problem:

```python
%matplotlib inline
from matplotlib import pyplot as plt
import numpy as np
import librosa
y, sr = librosa.load(librosa.util.example_audio_file())
S = np.abs(librosa.stft(y))
logamp = librosa.logamplitude(S**2)
n=3
plt.subplot(131)
plt.title('log')
librosa.display.specshow(logamp[:,:n], y_axis='log')
plt.subplot(133)
plt.title('linear')
librosa.display.specshow(logamp[:,:n], y_axis='linear')
plt.show()
```

**Comment by bmcfee** [comment]
Thanks for verifying.  I'll merge and close this one out.
