### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by kartikgupta0909** [bmcfee/librosa#317]
I was trying to build a recurrence matrix for a song and I got the MemoryError. I tried to print the dimensions of the array it was trying to build so it was 6293952 * 6293952. And as far as I calculated it requires somewhere around 1.584 * (10^14), which makes around 10^5 GB. I want to know if I am doing something wrong? or actually this feature cannot be calculated on normal machines. also pasting the log.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/librosa-0.4.2-py2.7.egg/librosa/segment.py", line 187, in recurrence_matrix
    D = scipy.spatial.distance.cdist(data, data, metric=metric)
  File "/home/kartik/.local/lib/python2.7/site-packages/scipy/spatial/distance.py", line 2079, in cdist
    dm = np.zeros((mA, mB), dtype=np.double)
MemoryError

**Comment by bmcfee** [comment]
This will most likely be resolved after we merge #313, which gives you the option of making sparse recurrence matrices.

Just to be clear though: were you building the recurrence matrix from the raw waveform data, or extracted features?

**Comment by kartikgupta0909** [comment]
On the raw waveform.

**Comment by stefan-balke** [comment]
> On the raw waveform.

Hm, this explains your memory error. Maybe you want to checkout some features like [MFCC](http://bmcfee.github.io/librosa/generated/librosa.feature.mfcc.html#librosa-feature-mfcc) or [Chroma](http://bmcfee.github.io/librosa/generated/librosa.feature.chroma_cqt.html#librosa-feature-chroma-cqt) first.

**Comment by kartikgupta0909** [comment]
Also, can i construct a recurrence matrix for some of the self computed feature vectors?

**Comment by bmcfee** [comment]
> Also, can i construct a recurrence matrix for some of the self computed feature vectors?

Yes, that is the most common way to do it.  The recurrence matrix tells you for each pair of frames `(i, j)` whether `j` is a near neighbor of `i`.  If your data are audio samples, then you're comparing one sample to another, which probably isn't meaningful; you're usually better off computing similarity between windows centered at samples `(i,j)`.

The example in the [documentation](http://bmcfee.github.io/librosa/generated/librosa.segment.recurrence_matrix.html) gives a complete walk-through of how this goes for MFCC features.

**Comment by stefan-balke** [comment]
Actually, why don't we have a simple SSM calculation in librosa?

**Comment by bmcfee** [comment]
> Actually, why don't we have a simple SSM calculation in librosa?

I try to minimize redundancy with existing tools, and simple SSM would be equivalent to `scipy.spatial.cdist`, right?

The recurrence matrix calculation is a little different, since it also builds in locality suppression.

**Comment by stefan-balke** [comment]
Well, yes, but then the recurrence calculations shouldn't take do it:
https://github.com/bmcfee/librosa/blob/master/librosa/segment.py#L187

It should rather take a SSM as input then.

But no rushing here, I'll tell you in a few days when I worked more with it...

**Comment by bmcfee** [comment]
> It should rather take a SSM as input then.

This is getting a little off-topic, but could you take a look at #313 ?  I'm replacing the explicit cdist call by wrapping to sklearn's nearest neighbor object.  This uses a spatial index structure to efficiently find nearest neighbors without explicitly constructing the distance matrix.  I don't think it will work with a self-sim matrix input.

**Comment by stefan-balke** [comment]
Oh, okay, I understand.
