### ISSUE TITLE
Calculating duration of audio file without having to load all samples

### ISSUE THREAD

**Issue by carlthome** [bmcfee/librosa#345]
Just curious if `get_duration()` could support getting the song duration without having to actually load all the samples into memory. I have a bunch of huge datasets of tracks that I'd like to get the total duration of and so on, but preferably without going through all of the material.

This for example, could work pretty well:
```Python
path = 'my_audio_file.wav'
def get_duration(path, bitdepth, samplerate):
    return os.path.getsize(path)/bitdepth*8/samplerate
```
assuming `bitdepth` and `samplerate` is known beforehand which is often the case.

It would totally break if the audio file is compressed though, but surely there must be a way to just look into the meta information of files? Maybe with ffmpeg (which is already a recommended install for librosa)?

**Comment by carlthome** [comment]
Or doesn't librosa already rely on audioread? Couldn't there be a `get_duration` that takes a path : str and just returns the duration directly via audioread then?

**Comment by bmcfee** [comment]
> Or doesn't librosa already rely on audioread? Couldn't there be a get_duration that takes a path : str and just returns the duration directly via audioread then?

Yeah, wrapping `audioread` for this would be totally reasonable and easy to do.  I think we can squeeze this into 0.4.3 without much effort.

The original applications that motivated `get_duration` all involved buffers already loaded in memory (and usually the output of other processing).  I see the need for what you're describing though.

**Comment by carlthome** [comment]
Sweet. Thanks @bmcfee!

**Comment by bmcfee** [comment]
fixed by merging #346

**Comment by realamirhe** [comment]
For anyone, which comes to this thread and wants more information, if you are going to sort lots of wav files which are all have same **sample size** and **sample rate** you can calculate the time, more easily like this


```py
import os

# audio_size = sample_rate (hz) * sample_size (bit) * time (s) * channels
average_sample_size = 4     # e.g. calculate it from random audio sample
average_sample_rate = 48000 # e.g. calculate it from random audio sample

def get_duration(path):
    return round(os.path.getsize(path) / average_sample_size / average_sample_rate, 3)

wavs = list(glob("./wavs/*.wav"))    
wavs.sort(key=get_duration)
``` 

see this [slides](https://www.slideshare.net/slideshow/calculate-audio-file-size/48660682) for more info

See this [article](https://www.tutorialspoint.com/how-to-get-the-duration-of-audio-in-python), learn how to get duration via other libraries

<details>
<summary>wave library</summary>

```py
import wave

def get_duration(file_path):
   with wave.open(file_path, 'r') as audio_file:
      frame_rate = audio_file.getframerate()
      n_frames = audio_file.getnframes()
      duration = n_frames / float(frame_rate)
      return duration
```
</details>


<details>
<summary>pydub library</summary>

```py
from pydub import AudioSegment

def get_duration(file_path):
   audio_file = AudioSegment.from_file(file_path)
   duration = audio_file.duration_seconds
   return duration
```
</details>

<details>
<summary>librosa library</summary>

```py
import librosa

def get_duration(file_path):
   audio_data, sample_rate = librosa.load(file_path)
   duration = librosa.get_duration(y=audio_data, sr=sample_rate)
   return duration
```
</details>


<details>
<summary>ffmpeg-python library</summary>

```py
import ffmpeg

def get_duration(file_path):
   probe = ffmpeg.probe(file_path)
   stream = next((stream for stream in probe['streams'] if stream['codec_type'] == 'audio'), None)
   duration = float(stream['duration'])
   return duration
```
</details>

**Comment by carlthome** [comment]
That's neat @realamirhe! Just a nitpick though that looking at the file size without subtracting the audio header bytes will lead to an incorrect duration, and you might also want to divide the number of bytes by number of audio channels for stereo or surround files.

**Comment by bmcfee** [comment]
Sorry, but I've hidden the above post to avoid proliferating incorrect results.  You really are better off using `get_duration` with the path option, which will use header info whenever possible to avoid a full load/decode.
