### ISSUE TITLE
ImportError: cannot import name core

### ISSUE THREAD

**Issue by wmaiouiru** [bmcfee/librosa#90]
Hello I upgraded librosa on Mac using the folllowing command: 
 sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install --upgrade librosa

However, when I am trying to import librosa, I am getting the following error. 
Any idea how to fix it? 
import librosa 
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/librosa/__init__.py", line 6, in <module>
    from . import core
ImportError: cannot import name core

**Comment by bmcfee** [comment]
@wmaiouiru @CVertex I believe this issue can be tracked down to cyclic imports.  I just finished a substantial refactoring of the development branch. Would you mind checking it out and testing whether or not this import error still exists?

Thanks!

**Comment by gauthamzz** [comment]
this problem still exists via installing via pip2

**Comment by bmcfee** [comment]
@gauthamzz please open a new issue -- whatever the problem is, it's not the same as the one originally reported here.

**Comment by nscozzaro** [comment]
I think I may be facing the same issue. I installed using pip. 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-c25ba87321a7> in <module>()
      7 import os
      8 import re
----> 9 import librosa
     10 import librosa.display
     11 import scipy

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/librosa/__init__.py in <module>()
     10 # And all the librosa sub-modules
     11 from . import cache
---> 12 from . import core
     13 from . import beat
     14 from . import decompose

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/librosa/core/__init__.py in <module>()
    106 """
    107 
--> 108 from .time_frequency import *  # pylint: disable=wildcard-import
    109 from .audio import *  # pylint: disable=wildcard-import
    110 from .spectrum import *  # pylint: disable=wildcard-import

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/librosa/core/time_frequency.py in <module>()
      8 import six
      9 
---> 10 from ..util.exceptions import ParameterError
     11 
     12 __all__ = ['frames_to_samples', 'frames_to_time',

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/librosa/util/__init__.py in <module>()
     68 from .files import *  # pylint: disable=wildcard-import
     69 from .deprecation import *  # pylint: disable=wildcard-import
---> 70 from . import decorators
     71 from . import exceptions
     72 

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/librosa/util/decorators.py in <module>()
     65 '''
     66 try:
---> 67     from numba.decorators import jit as optional_jit
     68 except ImportError:
     69     # Decorator with optional arguments borrowed from

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/numba/__init__.py in <module>()
     10 
     11 # Re-export typeof
---> 12 from .special import typeof, prange
     13 
     14 # Re-export error classes

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/numba/special.py in <module>()
      2 
      3 from .typing.typeof import typeof
----> 4 from .parfor import prange
      5 
      6 __all__ = ['typeof', 'prange']

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/numba/parfor.py in <module>()
     20 
     21 import numba
---> 22 from numba import ir, ir_utils, types, typing, rewrites, config, analysis
     23 from numba import array_analysis, postproc, typeinfer
     24 from numba.typing.templates import infer_global, AbstractTemplate

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/numba/ir_utils.py in <module>()
     10 import numba
     11 from numba.six import exec_
---> 12 from numba import ir, types, typing, config, analysis, utils, cgutils
     13 from numba.typing.templates import signature, infer_global, AbstractTemplate
     14 from numba.targets.imputils import impl_ret_untracked

/home/nscozzaro/anaconda3/lib/python3.5/site-packages/numba/cgutils.py in <module>()
     20 voidptr_t = int8_t.as_pointer()
     21 
---> 22 true_bit = bool_t(1)
     23 false_bit = bool_t(0)
     24 true_byte = int8_t(1)

TypeError: 'IntType' object is not callable

**Comment by arprasto** [comment]
I am also facing this while executing a python code in container env.
this is the env details:

absl-py==0.8.0
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.3
asn1crypto==0.24.0
astor==0.7.1
astroid==2.2.5
astropy==3.2.1
atomicwrites==1.3.0
attrs==19.1.0
audioread==2.1.6
Babel==2.7.0
backcall==0.1.0
backports.functools-lru-cache==1.5
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.7.1
bitarray==0.9.3
bkcharts==0.2
bleach==3.1.0
bokeh==1.2.0
boto==2.49.0
Bottleneck==1.2.1
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==1.2.1
clyent==1.2.2
colorama==0.4.1
conda==4.7.11
conda-build==3.18.8
conda-package-handling==1.3.11
conda-verify==3.4.2
contextlib2==0.5.5
cryptography==2.7
cycler==0.10.0
Cython==0.29.12
cytoolz==0.10.0
dask==2.1.0
decorator==4.4.0
defusedxml==0.6.0
distributed==2.1.0
docutils==0.14
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
Flask==1.1.1
Flask-Cors==3.0.8
future==0.17.1
gast==0.2.2
gevent==1.4.0
glob2==0.7
gmpy2==2.0.8
google-pasta==0.1.7
greenlet==0.4.15
grpcio==1.22.0
h5py==2.9.0
heapdict==1.0.0
html5lib==1.0.1
idna==2.8
imageio==2.5.0
imagesize==1.1.0
importlib-metadata==0.17
ipykernel==5.1.1
ipython==7.6.1
ipython-genutils==0.2.0
ipywidgets==7.5.0
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.13.3
jeepney==0.4
Jinja2==2.10.1
joblib==0.13.2
json5==0.8.4
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
jupyterlab==1.0.2
jupyterlab-server==1.0.0
Keras==2.2.5
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==18.0.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.1
libarchive-c==2.8
librosa==0.7.0
lief==0.9.0
llvmlite==0.29.0
locket==0.2.0
lxml==4.3.4
Mako==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.0
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.12
mkl-random==1.0.2
mkl-service==2.0.2
mock==3.0.5
more-itertools==7.0.0
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
navigator-updater==0.2.1
nbconvert==5.5.0
nbformat==4.4.0
networkx==2.3
nltk==3.4.4
nose==1.3.7
notebook==6.0.0
numba==0.44.1
numexpr==2.6.9
numpy==1.16.4
numpydoc==0.9.1
olefile==0.46
openpyxl==2.6.2
packaging==19.0
pandas==0.25.1
pandocfilters==1.4.2
parso==0.5.0
partd==1.0.0
path.py==12.0.1
pathlib2==2.3.4
patsy==0.5.1
pep8==1.7.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
pkginfo==1.5.0.1
pluggy==0.12.0
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.9.1
psutil==5.6.3
ptyprocess==0.6.0
py==1.8.0
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.3
pyflakes==2.1.1
Pygments==2.4.2
pygpu==0.7.6
pylint==2.3.1
pyodbc==4.0.26
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyrsistent==0.14.11
PySocks==1.7.0
pytest==5.0.1
pytest-arraydiff==0.3
pytest-astropy==0.5.0
pytest-doctestplus==0.3.0
pytest-openfiles==0.3.2
pytest-remotedata==0.3.1
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
PyYAML==5.1.1
pyzmq==18.0.0
QtAwesome==0.5.7
qtconsole==4.5.1
QtPy==1.8.0
requests==2.22.0
resampy==0.2.2
rope==0.14.0
ruamel-yaml==0.15.46
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.0
seaborn==0.9.0
SecretStorage==3.1.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.12.0
snowballstemmer==1.9.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
SoundFile==0.10.2
soupsieve==1.8
Sphinx==2.1.2
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.2
spyder==3.3.6
spyder-kernels==0.5.1
SQLAlchemy==1.3.5
statsmodels==0.10.0
sympy==1.4
tables==3.5.2
tblib==1.4.0
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
Theano==1.0.4
toolz==0.10.0
tornado==6.0.3
tqdm==4.32.1
traitlets==4.3.2
unicodecsv==0.14.1
urllib3==1.24.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.4
widgetsnbextension==3.5.0
wrapt==1.11.2
wurlitzer==1.0.2
xlrd==1.2.0
XlsxWriter==1.1.8
xlwt==1.3.0
zict==1.0.0
zipp==0.5.1

any input to resolve this ??

**Comment by bmcfee** [comment]
@arprasto the issue you're having is almost certainly not the same as the one originally reported here 5 years ago.  Please open a new issue with a complete traceback.
